<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    <link rel="stylesheet" href="carser.css">
<style>
*{
 margin: 0;
 padding: 0;   
}
body
{
    height: 100vh;
    background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('assets/jeep-wrangler-rubicon-5k-pe 1.jpg');
    background-position: center;
    background-size:cover;
     color:white;
    font-size:large;
     background-repeat:no-repeat;
    background-attachment: fixed;
}
.heading
{
  position: absolute;
  left: 10px;
  font-size: 15px;
}
h4
{
 color:purple;
}
#firsthead
{
    color:#fff;
    position: relative;
    left: 10px;
    top: 1px;
    font-size: 40px;
    text-decoration: none;
    font-family:Georgia, 'Times New Roman', Times, serif;
}
#secondhead
{
    color:#fff;
    position: relative;
    text-decoration: none;
    left: 10px;
    top: -2px;
    font-size: 18px;
    font-family:Georgia, 'Times New Roman', Times, serif;   
}
.navnames {
    width: 100%;
    overflow: auto;
    height: 70px;
  }

  .navnames a{
    float: right;
    text-align: center;
    padding: 12px;
    color: white;
    text-decoration: none;
    font-size: 17px;
    font-family:  -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  }

  .navnames a:hover {
    background-color: #000;
  }
  .aboutus
  {
    width:1180px;
    height:485vh;
    position:absolute;
    left:80px;
    top:170px;
    padding-right:50px;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0, 0.4);
    border: 1px solid black;
    border-radius: 1px;
    box-shadow: 10px 25px 30px rgba(0,0,0,0.3);
    font-family: Arial, Helvetica, sans-serif;
  }
  #aboutus1
  {
    position:absolute;
    top:120px;
    left:100px;
    font-size:40px;
    font-family: Arial, Helvetica, sans-serif;
  }
  .abouthead
  {
    position:relative;
    top:20px;
    left:30px;
    font-size:20px;
    font-family: Arial, Helvetica, sans-serif;
  }
  .aboutus2
  {
    position:relative;
    top:20px;
    left:20px;
    text-align:justify;
    line-height: 1.5;
    padding:10px;
    font-size:15px;
    bottom:10px;
  }
   #aboutus4
  {
    position:relative;
    top:20px;
    left:20px;
    text-align:justify;
    line-height: 1.5;
    padding:30px;
    font-size:15px;
  }
</style>
</head>
<body>
    <div class="container">
        <div class="heading">
       <a href="#" id="firsthead"> <b>Car Service Center</b></a><br>
       <a href="#" id="secondhead">A one stop solution for all brand car service</a>  
       </div>
       <div class="navnames">
        <a href="RegisterPage.jsp">Register</a>
        <a href="LogIn.jsp">Login</a>
        <a href="ContactUs.jsp">Contact Us</a>
        <a href="Index.jsp" >Home</a>          
       </div>
    </div>
     <%
   if(session.getAttribute("userinactive") != null){%>
	   <h1>Your Account is Successfully Removed!!</h1>
	   
   <%session.removeAttribute("userinactive"); }
   %>
   <h2 id="aboutus1">Terms of Use</h2> 
   <div class="aboutus">
    <h4 class="abouthead">CONTRACTUAL RELATIONSHIP</h4> 
           <p class="aboutus2">Targetone Innovations Private Limited, incorporated under the Companies Act, 2013, having its registered 
           office at Shop No. 8, Ramesh Market, Dayanand Colony, Lajpat Nagar, New Delhi - 110024, operating under the trademarked name 
           GoMechanic, provides holistic car services including maintenance, repair, etc. The use and access of our website www.gomechanic.in 
           Website, and our mobile applications GoMechanic - Car Services, Battery and Tyre Applications, or any products or services in
            connection with the Application or Website Services shall be governed by these terms and conditions Terms. The Website and Applications 
            are together called the Platform.</p>
<p class="aboutus2">No information provided on the Platform shall be considered a substitute for your independent investigation. 
These Terms are collectively an electronic record in terms of the Indian Contract Act, 1872; the Information Technology Act, 2000, 
the rules made thereunder; and the amended provisions pertaining to the electronic records in various other statutes as amended by 
the Information Technology Act, 2000. These Terms are generated by a computer system and do not require any digital or electronic signature.</p>

  <h4 class="abouthead">DEFINITIONS</h4> 
  
  <p class="aboutus2">Estimated Cost will include the service providers approximation of what the Service is likely to cost. The purpose of cost estimation 
  is to predict the quantity, cost, and price of the resources required to complete a job.</p>
  <p class="aboutus2">Service means services provided through the Platform, as described in further detail under Clause 3 below. The Services provided through 
  the Platform may change from time to time, at the sole discretion of the Company.</p>
            
    <h4 class="abouthead">SERVICES</h4> 
    
    <p class="aboutus2">The Services constitute a technology platform that enables Users of the Companys Platform, provided as part of the Services, to arrange
     and schedule repair or maintenance services for your car with independent third-party providers. Once you submit a request, we may provide you with a list 
     of possible service providers along with their experience information. </p>
     
 <p class="aboutus2">The Company also provides towing service to get your vehicle out of the situation and back on road on a chargeable basis.</p>
 
 <h4 class=abouthead>ELIGIBILITY</h4>
 
 <p class="aboutus2">You hereby represent and warrant that you are eighteen (18) years of age or above and are fully able and competent to understand and agree to the terms, conditions, obligations, affirmations, representations, and warranties set forth in these terms, and to abide by and comply with the Terms stated therein.
You are in compliance with all laws and regulations in the country in which you live when you access and use the Services.<br><br> You agree to use the Services only in compliance with these Terms and applicable laws, and in a manner that does not violate our legal rights or those of any third-parties.<br><br>
If you will be using the Services on behalf of an organization, you agree to these Terms on behalf of that organization and you represent that you have the authority to act on behalf of your organization.</p>
      
   <h4 class=abouthead>SUPPORT</h4> 
   <p class="aboutus2">The Company offers an email as well as phone call based support system along with an online knowledge pool of FAQs. In case you require any assistance or support, you may access support resources or contact our support by emailing at info@gomechanic.in or calling our helpline at +91-8398970970 (Monday to Sunday between 7 am and 9 pm).<br><br>

The Company shall revert to every complaint at the earliest upon receipt of the complaint during the business days. Further, the Company shall take the best possible efforts to redress the complaint within 7 days of receipt of the complaint. Any suggestions by the Company regarding the use of the Services shall not be construed as a warranty.</p>   
    
    <h4 class="abouthead">PROHIBITED USAGE OF THE PLATFORM</h4>      
    <p class="aboutus2">Users shall be prohibited from carrying out any illegal activity in the Platform including but not limited to acts mentioned are violating or attempting to violate the integrity or security of the Platform; transmitting any information on or through the Platform that is disruptive or competitive to the provision of our Services;
     intentionally submitting on the Platform any incomplete, false or inaccurate information; making any unsolicited communications to other Users; using any engine, software, tool, agent or other device or mechanism (such as spiders, robots, avatars or intelligent agents) to navigate or search the Platform; circumventing or disabling any digital rights
      management, usage rules, or other security features of the Platform. Any unlawful activities on the Platform are prohibited by the laws of India.</p>  
      
      <h4 class="abouthead">USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS</h4>
      <p class="aboutus2">You agree that no Comments submitted by you to the Platform will violate any right of any third party, including copyright, trademark, privacy or other personal or proprietary rights(s). You further agree that no Comments submitted by you to the Platform will be or contain libellous or otherwise unlawful, abusive or obscene material. You are and shall remain solely responsible for the content of any Comments you make.

<br><br>Additionally, you agree not to upload, post, e-mail or otherwise send or transmit any material designed to interrupt, destroy or limit the functionality of our service on the Platform. We may terminate or restrict your use of our Platform and Services if you violate these Terms or engage in any illegal or fraudulent use of our Platform or Services. </p>
      
        <h4 class="abouthead">USER DATA</h4>
      <p class="aboutus2">You represent and warrant that any information provided by you in connection with your use of the Platform is and shall remain true, accurate and complete and that you will maintain and update such information regularly. You agree that if any information you provide to us is false, inaccurate, obsolete or incomplete, we may terminate your use of and access to the Platform.

<br><br>You agree that the Company, may, in accordance with its Privacy Policy, collect and use your information, technical data, and related information for the validation of the documents submitted. The Company may use information and data pertaining to your use of the Services for analytics, trends identification, and purposes of statistics to further enhance the effectiveness and efficiency of the Platform and transfer the same to its group companies and service providers in furtherance of your access to these Services. You provide your consent to such use and sharing of your information.

      </p>
      
        <h4 class="abouthead">INTELLECTUAL PROPERTY RIGHTS</h4>
      <p class="aboutus2">The Platform is designed, updated and maintained independently by the Company. When you access the Platform, you do so under a license granted from us. All rights, titled and interest in text, graphics, audio, design and other works on the Platform together with all the intellectual property related thereto including inter alia the domain name, copyrights, the look and feel of the Platform, the trade name and trademarks, patents and designs are the sole property of the Company or its licensors. All third-party trademarks and brand names that appear on the Platform are the property of their respective owners. Content on the Platform is for personal use only, unless permitted otherwise. Any alteration of the material or use of the material contained in the Platform for any commercial purpose is a violation of the intellectual property of the Company and/or its affiliates or associates or of its third-party information providers. We reserve the right to suspend or cancel the service at any time if a computer virus, bug, or other technical problem corrupts the security or proper administration of the service.

<br><br>You acknowledge and agree that through your use of the Platform or by availing any Services through or at the Platform, no right (empress or implied) is granted to you in respect of such Content. The Company reserves the right to change or modify the Content from time to time at its sole discretion.

      </p>
      
        <h4 class="abouthead">LICENSE</h4>
      <p class="aboutus2">Subject to your compliance with these Terms, the Company grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable licence to (i) access and use the Applications on your personal device solely in connection with your use of the Services; and (ii) access and use any content, information, and related materials that may be made available through the Services, in each case, solely in connection with your use of the Services. The Company and its licensors reserve all rights not expressly granted herein.

<br><br>You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Platform and Services, except as expressly permitted in the Terms and Conditions. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by the Company or its licensors, except for the licenses and rights expressly granted in the Terms and Conditions. The Platform and the intellectual property rights vested therein are owned by the Company.</p>
      
        <h4 class="abouthead">LIMITATION OF LIABILITY</h4>
      <p class="aboutus2">In no case are our directors, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors, liable for indirect, incidental, special, exemplary, punitive or consequential damages, including lost profits, lost data, personal injury or property damage related to, in connection with, or otherwise resulting from any use of the Services, even if the Company has been advised of the possibility of such damages.

<br><br>The Company shall not be liable for any damages, liability or losses arising out of your use of or reliance on the Services or your inability to access or use the Services; or any transaction or relationship between you and any third-party provider or any delay or failure in performance resulting from causes beyond Companys reasonable control.

      </p>
      
        <h4 class="abouthead">EXEMPTIONS TO LIABILITY OF COMPANY</h4>
      <p class="aboutus2">User further agrees and confirms that the Company shall not be responsible, in any manner whatsoever, for any delay,unavailability of Services or failure to meet its obligations under the Terms and Conditions, which may be caused, directly or indirectly, due to: your failure to cooperate; your unavailability and/or unresponsiveness; your failure to provide accurate and complete information; your failure to provide or facilitate the submission of User materials in a timely manner; or any event beyond the Companys reasonable control.

<br><br>User further agrees that the Company shall be only liable to provide assistance and cooperation in the event of theft or accident of the vehicles while in the premises of the service partners. The Company shall provide all requisite assistance in a timely manner in respect of any insurance claims, reporting to police and/or any other formal steps as may be required but shall not be liable to compensate the User for its loss unless the same is caused due to an act solely attributable to the Company or due to gross negligence of Company (and not the service partner).</p>
      
        <h4 class="abouthead">BILLING/CHARGES</h4>
      <p class="aboutus2">You acknowledge that by using the Services, you may be subject to charges from a third-party service provider for the services you receive ("Charges"). The Company, as a limited payment collection agent for a third-party service provider, will facilitate your payment of the applicable Charges after you have received services through your use of the Service. The Charges will be handled as if you had directly paid the third-party service provider. All Charges will include all applicable taxes unless otherwise specified by law. Unless otherwise stated by the Company, all Charges paid by you are final and non-refundable. 

<br><br>The Charges may be updated or changed at any time as per the analysis of the third-party services provider or your new requests. The updated Charges shall be communicated to you by the Company and only upon your approval of the Charges, the services will be provided by the third-party service provider. 

<br><br>You acknowledge that the Charges from a third-party service provider shall be duly paid and on account of default in payment, the same shall be considered as a breach of these terms. In the event you commit such a default/breach, you shall be liable to pay the liquidated damages of an amount equivalent to the value of the said services. You hereby authorize the Company to deduct or collect the amount payable as liquidated damages through such means as the Company may exercise.

<br><br>In case of any material changes have been made and there is a default in payment by the User, the Company has a right to keep the vehicle in its possession until and unless payment in full has been made by the User along with other costs if applicable. In the event you fail to make the payment of the Charges despite the passage of more than 90 days since the completion of the services, the Company shall be entitled to recover the same by selling off your vehicle.

<br><br>You acknowledge that you will be liable for the payment of towing services provided by the Company as per the Companys Charges.

<br><br>Membership Plans will be offered by the company from time to time through its website, app, social and print media. You can purchase the membership through the Platform by adding it into the cart, checking out and making the payment.

<br><br>The Company reserves the right to alter/modify/suspend/discontinue any terms and conditions associated with the Fee including but not limited to the period, rate, services included in the membership. Further, the Company shall give you notice of any change made to the features of the membership prior to the expiry of the same. We will provide you with advance notice of any change in Fees.</p>
 </div>
</body>
</html>